### ISSUE TITLE
Rsync Failure for /vagrant on MacOS

### ISSUE THREAD

**Issue by WammKD** [palfrey/guix-vm#13]
I'm not sure if it's specific to Mac (I can't test on any other machine, I'm afraid, but I assume it's working for you) but I get this error when I try including the bit given in the README for setting up the `/vagrant` directory:

```
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /Users/wammkd/v/
Guest path: /vagrant
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2222 -o LogLevel=FATAL   -o ControlMaster=auto -o ControlPath=/var/folders/pd/d549c4910dbcnrft98pvcgrr0000gn/T/vagrant-rsync-20220126-48360-12rlrla -o ControlPersist=10m  -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/Users/wammkd/v/.vagrant/machines/default/virtualbox/private_key'" "--exclude" ".vagrant/" "--exclude" ".git/" "/Users/wammkd/v/" "vagrant@127.0.0.1:/vagrant"
Error: rsync: This rsync lacks old-style --compress due to its external zlib.  Try -zz.
rsync error: syntax or usage error (code 1) at main.c(1578) [server=3.1.3]
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/io.c(453) [sender=2.6.9]
```

**Comment by palfrey** [comment]
This appears to be an upstream bug (https://github.com/hashicorp/vagrant/issues/9221 among others). Not sure there's a fix that can be applied here!

**Comment by WammKD** [comment]
Huh; well, damn. I'd been hoping I'd be able to shift our work VM over to Guix but 'can't really go anywhere with it without this feature. Oh, well.

Thanks a ton for figuring that out for me; and for creating this! It's really cool that Guix is available for Vagrant.

**Comment by palfrey** [comment]
There's also a reference in #1 to a Guix config from elsewhere that appears to have solved the Guest Additions problem which would fix this. I haven't had the time to investigate, but patches welcomed!
