### ISSUE TITLE
Road to Guix v1.3.0

### ISSUE THREAD

**Issue by OverkillGuy** [palfrey/guix-vm#9]
Hello again! Just fresh from me bothering y'all for a 1.2 release, [the Guix project released v1.3.0](https://guix.gnu.org/en/blog/2021/gnu-guix-1.3.0-released/) today.

Let's map out what's required to make 1.3 work!

**Comment by palfrey** [comment]
A lot like the 1.2.0 upgrade. So, fix the iso url and checksum (ee71defba246c23e59726b7f9bc1644ef893bbf0), up the branch version (442b60fb87ccc0d175cf9ff6d346fe91932e559f, well parts of that), and then fix whatever stops `packer build guix-vm.json` from working.

I'm unlikely to get to this anytime soon, but if you can fix those bits, I can upload a 1.3.0 image once you're done.

**Comment by OverkillGuy** [comment]
Sounds good, I had already done some of that offline, just pushed it as PR. 

There's a little bit to discuss on it (like removal of the explicit branch name in channel, to rely on default) but this should be okay.

**Comment by palfrey** [comment]
Released as https://app.vagrantup.com/palfrey/boxes/guixsd/versions/1.3.0
